#!/usr/bin/env sh
displayCount=$((`xrandr -q|grep " connected"|wc -l`))

xrandr --auto

OUT0=eDP-1
OUT1=DVI-I-3-2
OUT2=DVI-I-2-1

if [ $displayCount -eq 3 ]; then
    notify-send "Enabling monitor dock mode 3 displays"
    xrandr --auto --output $OUT1 --primary --mode 1920x1080 --right-of $OUT0 --rotate normal --output $OUT2 --mode 1920x1080 --right-of $OUT1 --rotate normal
    xrandr --output $OUT2 --primary
elif [ $displayCount -eq 2 ]; then
    notify-send "Enabling two display, external above internal"
    xrandr --auto --output $OUT2 --mode 1920x1080 --rotate normal --above $OUT0 --scale 1x1
    xrandr --output $OUT2 --primary
elif [ $displayCount -eq 1 ]; then
    xrandr --output $OUT0 --primary
fi

sleep 1
notify-send "Setting rate 300 50"
xset r rate 300 50
killall -USR1 i3status
